### ISSUE TITLE
Finishing Deck Error

### ISSUE THREAD

**Issue by MtnManBearPig** [AnKing-Memberships/The-KING-of-Button-Add-ons#12]
AnKingMed,

I have noticed that once I finish my reviews for the day, I review an error code on the "Congratulations! You have finished this deck for now." screen.

This is what the Error code says: "
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-16 17:55:07

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 493, in handler
  File "aqt\reviewer.py", line 329, in _onAnswerButton
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-30>", line 2, in _answerCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 633, in repl
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-26>", line 2, in _answerCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 632, in repl
  File "C:\Users\noahk\AppData\Roaming\Anki2\addons21\374005964\confirmation.py", line 26, in answerCard_before
    answerButtons = self._answerButtonList()
  File "aqt\reviewer.py", line 626, in _answerButtonList
  File "anki\schedv2.py", line 198, in answerButtons
  File "anki\schedv2.py", line 1199, in _cardConf
AttributeError: 'NoneType' object has no attribute 'did'
"

I have uninstalled and reinstalled the add on hoping that it would fix it, but unfortunately nothing has worked. Please let me know what I need to do in order to fix this. 

Thank you for everything that you and your team do!
-MMBP

**Comment by AnKingMed** [comment]
Hmm I have never seen this error but I'll look into it.  Can you test one thing for me? Will you see if this error still occurs if only this add-on is installed and all others are toggled off?

**Comment by MtnManBearPig** [comment]
AnKingMed,

I just disabled all of my add ons except for 'The KING of Button Add-ons' and I am still getting the error code.

This is what it says:'
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-16 17:55:07

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 493, in handler
  File "aqt\reviewer.py", line 329, in _onAnswerButton
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-2>", line 2, in _answerCard
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 632, in repl
  File "C:\Users\noahk\AppData\Roaming\Anki2\addons21\374005964\confirmation.py", line 26, in answerCard_before
    answerButtons = self._answerButtonList()
  File "aqt\reviewer.py", line 626, in _answerButtonList
  File "anki\schedv2.py", line 198, in answerButtons
  File "anki\schedv2.py", line 1199, in _cardConf
AttributeError: 'NoneType' object has no attribute 'did'
'

Please let me know what I need to do next to resolve this.

Thank you!
-MMBP

**Comment by AnKingMed** [comment]
Hmm... I can't replicate this error on mine and I don't have access to a windows.  Do you know of anyone else that has had this problem?  When did it start? Does it work on previous versions? I'll keep looking into it.
